title: Sumeet's blog
email: sumeet.mathpati@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A simple and minimal jekyll theme.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sumeetmathpati.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  sumeetmathpati
permalink: /:title/
include: ["_pages"]
google_analytics_id: "UA-178663162-1" # Example, UA-**********-*

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-paginate


jekyll-archives:
  enabled:
    - categories
  layout: 'page'
  layouts:
    year: year
    month: month
    tag: tag_and_category
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    tag: '/tag/:name/'
    category: '/category/:name/'