title: Sumeet's blog
email: sumeet.mathpati@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A simple and minimal jekyll theme.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sumeetmathpati.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  sumeetmathpati
permalink: /:title/
include: ["_pages"]
favicon: "./logo.png" # relative path to site's favicon
goat_counter: "sumeet" # put your GoatCounter name if you want to use GoatCounter analytics
google_ad_sense_client_id: ca-pub-2723808074010055

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap


# Pagination 
paginate: 10
paginate_path: /page:num/