baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
publishDir = 'docs'

[params]
custom_css = ["css/style.css"]
custom_js = ["js/main.js"]



[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokai'
    tabWidth = 4

